<?php

namespace App\Services\ImageProcessor;

use App\Services\ImageProcessor\Contracts\ScriptGeneratorInterface;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Process;

/**
 * Generic ImageMagick script executor.
 *
 * This service generates and executes ImageMagick scripts
 * using pluggable generators for different techniques.
 */
class ImageMagickService
{
    public function __construct(
        private readonly string $binary = 'magick',
    ) {}

    /**
     * Generate scripts using the specified generator.
     *
     * @param ScriptGeneratorInterface $generator The technique generator to use
     * @param array $groups Grouped/classified images
     * @param array $config User configuration for the generator
     * @param string $imageDirectory Base directory containing source images
     * @param string $scriptsDirectory Where to save .mgk scripts
     * @param string $outputDirectory Where final images should be saved
     * @return array Array of generated script paths
     */
    public function generateScripts(
        ScriptGeneratorInterface $generator,
        array $groups,
        array $config,
        string $imageDirectory,
        string $scriptsDirectory,
        string $outputDirectory
    ): array {
        File::ensureDirectoryExists($scriptsDirectory);
        File::ensureDirectoryExists($outputDirectory);

        $generatedScripts = [];
        $prefix = $config['output_prefix'] ?? $generator->getKey();

        foreach ($groups as $groupNumber => $group) {
            $paddedGroup = str_pad($groupNumber, 2, '0', STR_PAD_LEFT);
            $outputPath = "{$outputDirectory}/{$prefix}_{$paddedGroup}.jpg";

            // Prepare image paths (make them absolute if needed)
            $preparedGroup = $this->prepareImagePaths($group, $imageDirectory);

            // Generate the script content
            $scriptContent = $generator->generateScript(
                $preparedGroup,
                $config,
                $outputPath
            );

            // Save script to file
            $scriptPath = "{$scriptsDirectory}/{$generator->getKey()}_{$paddedGroup}.mgk";
            File::put($scriptPath, $scriptContent);

            $generatedScripts[] = $scriptPath;
        }

        // Generate master execution script
        if (!empty($generatedScripts)) {
            $this->generateMasterScript($scriptsDirectory, $generatedScripts, $generator->getName());
        }

        return $generatedScripts;
    }

    /**
     * Prepare image paths - convert relative paths to absolute if needed.
     *
     * @param array $group Group of classified images
     * @param string $imageDirectory Base image directory
     * @return array Group with absolute file paths
     */
    private function prepareImagePaths(array $group, string $imageDirectory): array
    {
        $prepared = [];

        foreach ($group as $classification => $files) {
            $prepared[$classification] = array_map(
                fn($file) => $this->makeAbsolutePath($file, $imageDirectory),
                $files
            );
        }

        return $prepared;
    }

    /**
     * Make a file path absolute if it's not already.
     *
     * @param string $file Filename or path
     * @param string $baseDirectory Base directory to use for relative paths
     * @return string Absolute path
     */
    private function makeAbsolutePath(string $file, string $baseDirectory): string
    {
        // If already absolute, return as-is
        if (str_starts_with($file, '/') || preg_match('/^[A-Z]:/i', $file)) {
            return $file;
        }

        // Make it absolute
        return "{$baseDirectory}/{$file}";
    }

    /**
     * Generate master execution script.
     *
     * @param string $scriptsDirectory Directory containing scripts
     * @param array $scriptPaths Array of script paths to execute
     * @param string $techniqueName Name of the technique for display
     */
    private function generateMasterScript(
        string $scriptsDirectory,
        array $scriptPaths,
        string $techniqueName
    ): void {
        $lines = [];
        $lines[] = "#!/bin/bash";
        $lines[] = "set -e";
        $lines[] = "";
        $lines[] = "# Master script for {$techniqueName}";
        $lines[] = "# Generated by ImageProcessor";
        $lines[] = "";
        $lines[] = "echo \"Starting {$techniqueName} processing...\"";
        $lines[] = "";

        foreach ($scriptPaths as $index => $scriptPath) {
            $groupNum = $index + 1;
            $basename = basename($scriptPath);

            $lines[] = "echo \"Processing group {$groupNum} ({$basename})...\"";
            $lines[] = "{$this->binary} -script \"{$scriptPath}\"";
            $lines[] = "if [ \$? -eq 0 ]; then";
            $lines[] = "    echo \"  ✓ Group {$groupNum} completed\"";
            $lines[] = "else";
            $lines[] = "    echo \"  ✗ Group {$groupNum} failed!\" >&2";
            $lines[] = "    exit 1";
            $lines[] = "fi";
            $lines[] = "";
        }

        $lines[] = "echo \"All groups completed successfully!\"";

        $masterPath = "{$scriptsDirectory}/run_all_scripts.sh";
        File::put($masterPath, implode("\n", $lines));
        chmod($masterPath, 0755);
    }

    /**
     * Execute all scripts via the master script.
     *
     * @param string $scriptsDirectory Directory containing the master script
     * @return array Result with success, output, error, and exit_code
     */
    public function executeAllScripts(string $scriptsDirectory): array
    {
        $masterScript = "{$scriptsDirectory}/run_all_scripts.sh";

        if (!file_exists($masterScript)) {
            return [
                'success' => false,
                'error' => 'Master script not found at: ' . $masterScript,
                'output' => '',
                'exit_code' => 1,
            ];
        }

        // Execute with 30 minute timeout
        $result = Process::timeout(1800)->run("bash \"{$masterScript}\"");

        return [
            'success' => $result->successful(),
            'output' => $result->output(),
            'error' => $result->errorOutput(),
            'exit_code' => $result->exitCode(),
        ];
    }

    /**
     * Execute a single script.
     *
     * @param string $scriptPath Path to the .mgk script
     * @return array Result with success, output, error, and exit_code
     */
    public function executeScript(string $scriptPath): array
    {
        $result = Process::run("{$this->binary} -script \"{$scriptPath}\"");

        return [
            'success' => $result->successful(),
            'output' => $result->output(),
            'error' => $result->errorOutput(),
            'exit_code' => $result->exitCode(),
        ];
    }
}
